### ISSUE TITLE
Cannot derive large nested enums

### ISSUE THREAD

**Issue by grzegorz-bielski** [MartinHH/scalacheck-derived#115]
Hello!

First of all, thanks for this library and all the effort you put into it! 🙇 

I noticed deriving `Arbitrary` for nested enums sometimes fails, for example:

```scala
//> using scala "3.3.5"
//> using dep io.github.martinhh::scalacheck-derived:0.8.1

import io.github.martinhh.derived.scalacheck.deriveArbitrary
import org.scalacheck.Arbitrary

sealed trait NestedEnum
object NestedEnum:
    sealed trait NestedEnumInner extends NestedEnum
    object NestedEnumInner:
        case object `1` extends NestedEnumInner
        case object `2` extends NestedEnumInner
        case object `3` extends NestedEnumInner
        case object `4` extends NestedEnumInner
        case object `5` extends NestedEnumInner
        case object `6` extends NestedEnumInner
        case object `7` extends NestedEnumInner
        case object `8` extends NestedEnumInner
        case object `9` extends NestedEnumInner
        case object `10` extends NestedEnumInner
        case object `11` extends NestedEnumInner
        case object `12` extends NestedEnumInner
        case object `13` extends NestedEnumInner
        case object `14` extends NestedEnumInner
        case object `15` extends NestedEnumInner
        case object `16` extends NestedEnumInner
        case object `17` extends NestedEnumInner
        case object `18` extends NestedEnumInner
        case object `19` extends NestedEnumInner
        case object `20` extends NestedEnumInner
        case object `21` extends NestedEnumInner
       
given Arbitrary[NestedEnum] = deriveArbitrary // err: No given instance of type Summoner[NestedEnum.NestedEnumInner] was found. 
```

This starts working again as soon as you comment out the ```case object `21` extends NestedEnumInner```.
It also fails with other configurations like (many) more inner nested enums, but with less fields.

The above works fine under `3.6.4`, but I cannot use it in my shared library.

**Comment by MartinHH** [comment]
Hi! My initial thought while on the phone (i.e. without being able to reproduce) is that this a hidden case of the "[max-inline-problem](https://github.com/MartinHH/scalacheck-derived?tab=readme-ov-file#maximal-number-of-successive-inlines)".

Otherwise, it would be a regression introduced in 0.7.0 (by optimizations for Scala 3.4.0 or higher).
Could you try increasing `-Xmax-inlines` to 33 and check if that increases the limit you observed from 21 to 22?

**Comment by grzegorz-bielski** [comment]
Yeah, looks like adding ```//> using options -Xmax-inlines 33``` to the above snippets helps with the problem. 

But I also noticed that it works fine with `0.6.0` without changing `max-inline` compiler options, so it could also be considered as regression.

If fixing it for `3.5.5` is too bothersome, then it'd be useful to at least mention it in the compilation error and / or docs.

**Comment by MartinHH** [comment]
Another option how to solve this would be to lobby for a backport of the change that causes this to work with 3.4.0 back to 3.3.x [here](https://github.com/scala/scala3/issues/15988) - but personally, I'd rather see anyone who is capable of contributing to scala work towards a next LTS than this.
